version: '2'
services:
    todos-app:
        image: todos
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://todos-postgresql:5432/todos
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=todos-elasticsearch:9300
        ports:
            - 8080:8080
    todos-postgresql:
        extends:
            file: postgresql.yml
            service: todos-postgresql
    todos-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: todos-elasticsearch
